export const subjects = {
  prelims: [
    { name: 'History of India and Indian National Movement' },
    { name: 'Indian and World Geography' },
    { name: 'Indian Polity and Governance' },
    { name: 'Economic and Social Development' },
    { name: 'General issues on Environmental Ecology, Bio-diversity and Climate Change' },
    { name: 'General Science' },
    { name: 'Current events of national and international importance' },
  ],
  mains: [
    { name: 'Essay' },
    { name: 'Indian Heritage and Culture, History and Geography of the World and Society' },
    { name: 'Governance, Constitution, Polity, Social Justice and International relations' },
    { name: 'Technology, Economic Development, Bio diversity, Environment, Security and Disaster Management' },
    { name: 'Ethics, Integrity, and Aptitude' },
  ],
  optional: [
    { name: 'Agriculture' },
    { name: 'Animal Husbandry & Veterinary Science' },
    { name: 'Anthropology' },
    { name: 'Botany' },
    { name: 'Chemistry' },
    { name: 'Civil Engineering' },
    { name: 'Commerce and Accountancy' },
    { name: 'Economics' },
    { name: 'Electrical Engineering' },
    { name: 'Geography' },
    { name: 'Geology' },
    { name: 'History' },
    { name: 'Law' },
    { name: 'Management' },
    { name: 'Mathematics' },
    { name: 'Mechanical Engineering' },
    { name: 'Medical Science' },
    { name: 'Philosophy' },
    { name: 'Physics' },
    { name: 'Political Science and International Relations' },
    { name: 'Psychology' },
    { name: 'Public Administration' },
    { name: 'Sociology' },
    { name: 'Statistics' },
    { name: 'Zoology' },
  ],
};
