[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 